### ISSUE TITLE
feature: migrate rupture rate filtered functions from solvis-graphql-api

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/solvis#37]
This is part one of epic #30

**done when:**
 - [x] migrate `cached.get_rupture_ids_for_location_radius function`
 - [x] migrate `cached.get_rupture_ids_for_fault_names`
 - [x] modify filtering args to use simple `python enum`
 - [x] add unit test coverage and docstrings for above

NB given that this filtering logic can be applied to any dataframe returning `rupture` information consider refactoring to make this more generalised (maybe a new ticket, but lets think about it now).

**Comment by DrCuriosity** [comment]
@chrisbc, just to be clear on where we're putting these functions: I'm guessing in `InversionSolutionOperations`?

There are a couple of `get_ruptures_...` functions there already, so it seems like a good fit. 

I'm also wondering if it might be good to rename those existing functions to `get_rupture_ids_...` so that they're more consistently and explicitly named? If I do that, I'll be passing the original method names through to the renamed methods with a `DeprecationWarning`, so that things keep working but anyone depending on the old names can clean things up more easily.
