### ISSUE TITLE
SPIKE: 3D visualisation for solvis/geojson fault surfaces

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/solvis#43]
We want web-browser visualiation of fault surfaces that will improve the user experience relative to our current 2D leaflet based rupture map explorer:

**Features sought:**
 - environments:  standalone HTML, Jupyter notebooks, React (for Weka/Kororaa) 
 - can do everything that Rupture Explorer does:
    - set initial user viewport, zoom etc
    - full-screen option
    - stepping through ruptures in sequence   
    - user zoom, pan etc
    - map layer/tiles for flexible surface details 
    - multiple geojson layers (fault surface + rupture)
    - click in feature for more info
    - add widget (plots etc)
- plus 3D

**Try:**
  - cesium
  - mapbox (https://www.mapbox.com/mapbox-gljs)

**things to consider:**
 - is licensing compatible with GNS NSHM needs
 - independence from proprietary backend server/services
 - ease of use
 - compatability with existing stack
 - customisation

**Comment by voj** [comment]
Investigated:
- MapLibre/Mapbox
- CesiumJs
- ArcGIS

All libraries fulfill most requirements. I will only list problems here.

- `MapLibre` is an open source fork of `MapBox`. No built-in GeoJSON layer. Needs to be implemented in `three.js`. Did not have enough time to solve clipping problem. Bare-bones functionality since we need to implement our own low-level GeoJson layer.
- `CesiumJS` has support for underground rendering, ticks all the boxes. Active community support, Cesium team are actively answering questions in forum. Only drawback is unintuitive navigation and ugly timeline animator.
- `ArcGIS` ticks all the boxes. Beautiful underground navigation. Requires us to use in conjunction with other ArcGIS products. Could probably be satisfied by pulling map tiles from GNS arc server.

There are demos for CesiumJS and ArcGIS: https://github.com/daily-science/solvis-jupyterlab/pull/1

**Comment by voj** [comment]
We decided to go with `CesiumJS`. We will create a new repo for a Juptyer Notebook widget to consolidate the work from the spike.
